timeout:
  type: 
    __type: string
  amount: 
    __type: int
  enabled: 
    __required: false
    __type: bool
  logging:
    connstring:
      __type: string

database:
  connstring:
    __type: string
  tables:
    __type: array